### ISSUE TITLE
Delete Icon in the Saved Sets pane is not working.

### ISSUE THREAD

**Issue by aazaff** [ngds/ADEPT_frontend#12]
![Screenshot 2021-07-01 at 9 44 43 AM](https://user-images.githubusercontent.com/10422595/124160299-f9e97e80-da50-11eb-941c-6bfb19c46604.png)

The little trash icons indicate that you should be able to remove unwanted searches from the list, but nothing happens if you click them.

**Comment by aazaff** [comment]
@Lbookman fixed this, waiting for commit before closing issue.

**Comment by Lbookman** [comment]
fixed issue
