### ISSUE TITLE
Finalized list of form requirements for application submission

### ISSUE THREAD

**Issue by aazaff** [ngds/ADEPT_frontend#15]
````JSON
{
  "user_name" : "Name of user",
  "user_id" : "ADEPT internal id",
  "user_email" : "User email address (auto popuplated?)",
  "app_name": "Name of application",
  "app_description" : "Short summary of the goal(s) of the application",
  
  "docker_image" : "...",
  "docker_image_checksum" : "...",
  
  "resource_cpu" : "Required number of CPUs (default: 1)",
  "resource_memory" : "Required amount of memory (default: 4GB)",
   
   "github_repo" : "Link to github repo", -- Optional
  "resource_runtime" : "Estimated/expected runtime" -- Optional
}
````

**Comment by aazaff** [comment]
Looking more closely at the list provided by @iross I feel that there is a lot missing here that should be included. Particularly when comparing it to the instructions provided in the xDD docker recipe [readme](https://github.com/UW-xDD/xdd-docker-recipe#communicating-application-behavior). Almost none of the questions those instructions ask are answered by the form.

> The first step in the process is to communicate the application behavior to the xDD team.
What does the application do?
What data product(s) are needed for an input?
How is the target corpus defined? (keyword, set of keywords, defined list of DOIs, specific journal, etc.)
What are the approximate resources required for the application?
Does the application require access to all desired data at once, or can it be split into smaller datasets?

![Screenshot 2021-07-29 at 11 22 25 AM](https://user-images.githubusercontent.com/10422595/127545526-5ac02daa-12ac-4163-ac0c-fa1cdc5d1aa7.png)

Here are my suggestions for improvements.
1. The Applications description text-box displays as very tiny. I think the textbox should be much larger and possibly extendable to encourage users (or at least let them know that it is permissable) to write application descriptions that are longer than a few words.
2. Optional vs required fields should be visually flagged in some way.
3. The **Resources Required to Execute* field should be changed to **Estimated Computing Requirements** to specify that that the user doesn't need to know exactly what will be required.
4. There should be a field for users to specify the *default* ADEPT saved-set that should be paired with the application.

@iross please evaluate these suggestions and let me know right away if you agree.

**Comment by aazaff** [comment]
Add `output_link` field to database table `user_app_instance` and also make sure said field displays in application.

**Comment by Lbookman** [comment]
added output_link to the result field and added test set to register application form
