### ISSUE TITLE
Show Search and Save Search should be separated

### ISSUE THREAD

**Issue by aazaff** [ngds/ADEPT_frontend#21]
**It is too late for us to change this now**, but I just wanted to make a note that the way the "save search" and "display search" works as it is currently implemented isn't ideal.

This is how it should be.
![Example](https://user-images.githubusercontent.com/10422595/129595913-8795d052-62ab-49cf-9844-bcb88d963ddf.png)

With the SAVE options clearly separated from the LOAD options.

**Comment by GaryHudmanAZGS** [comment]
Fixed by adding a pop-up form for Save Search...
