### ISSUE TITLE
Update to loginPanel help page

### ISSUE THREAD

**Issue by aazaff** [ngds/ADEPT_frontend#7]
## About
This **A**utomated **D**ata **E**xtraction **P**la**T**form is a set of webtools to facilitate access to the xDD library of full-text documents (https://xdd.wisc.edu). xDD is the largest collection of open and controlled-access scientific articles available for bulk text data-mining in the world.

Machine-learning researchers can use ADEPT to:
1.  SEARCH xDD metadata records
2. Create a SAVED SET of one or *more* search results
3. Request a TEST SET of 200 random documents from a saved set for local development purposes.
4. Submit APPLICATIONS for high-throughput deployment on the entire xDD library
5. Share saved sets, test-sets, and applications with GROUPS of collaborators

### SAVED SET
A user may save the results of one or more metadata searches as a SAVED SET. Saved Sets are created in the saved sets tab, then populated by saving searches and citations on the Search page. The search parameters in a saved set can be also be used to access the xDD API directly to access the same data directly from the source.

### TEST SET
xDD must control access to its resources to ensure that they are used for legitimate scientific research in bulk text data-mining and that xDD is not used by bad-actors to circumnavigate normal licensing restrictions (i.e., to download PDFs that they would not normally have legal access to for purposes other than text data-mining). xDD fulfils this responsibility by ensuring that its full-text documents do not leave its servers. 

An exception to this rule are test-sets that ADEPT users may use for local development of xDD APPLICATIONS. A test-set is a random sample of 200 documents from a SAVED SET that a user may download onto their local machines for development purposes. New test sets can be requested from the SAVED SETS or DICTIONARIES tab. Once approved by the xDD system, users can find a unique API-key and URL to to their requested test-set in the TEST SETS tab. 

## DICTIONARIES
Dictionaries are a collection of search terms, and can be either xDD identified Dictionaries, or user constructed dictionaries. Dictionaries can also be used as the source for the creation of TEST SETS, which are a data product identified in the GeoDeepDive system used in ML processing.

### APPLICATIONS
ADEPT defines an xDD application as a dockerized set of machine-learning scripts for the purpose of bulk text data-mining. xDD administrators need to monitor whether a submitted text data-mining application is respectful of its [Terms of Service](https://github.com/ngds/ADEPT_frontend/blob/main/TOS.md). Users can use the applications tab to submit an application for review and approval by an xDD administrator or to request that an already approved application be deployed on the xDD high-throughput computing architecture.

### GROUPS
A user may create a GROUP of collaborators to share items with (i.e., SETS, TEST SETS, and APPLICATIONS). Group members have full edit privileges for shared items and may add, edit, or delete items within a group. Note that deleting a shared item will delete that item for all users.

**Comment by aazaff** [comment]
In addition to updating this help page, would it be possible to hide or disable the "Status" and "Upload Document" buttons?

**Comment by GaryHudmanAZGS** [comment]
Complete...
